CREATE TABLE facultades ( 
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(500),
    ubicacion GEOGRAPHY(POINT,4326),
    descripcion VARCHAR(3000),
    imagen VARCHAR(500)
  );

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (1, 'Escuela Politécnica Superior', 
(ST_SetSRID(ST_MakePoint(40.512869, -3.348754), 4326)::geography), '<br>Edificio Politécnico<br>Calle 18<br>Ctra Madrid - Barcelona Km 33,600<br>28805 Alcalá de Henares, Madrid<br><br><a href="http://www.uah.es/escuela-politecnica/" target="_blank">Ver Página</a><br><br>Titulaciones en el edificio:<br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=210&plan=G59&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Ingeniería de Computadores</a><br>-  <a href="http://www.uah.es/estudios/grados/planes.asp?cd=203&plan=G37&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Ingenieria Electrónica de Comunicaciones</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=203&plan=G60&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Ingeniería en Electrónica y Automática Industrial</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=203&plan=G39&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Ingeniería en Sistemas de Telecomunicación</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=203&plan=G35&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Ingeniería en Tecnologías de la Telecomunicación</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=210&plan=G780&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Ingeniería Informática</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=203&plan=G38&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Ingeniería Telemática</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=210&plan=G58&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Sistemas de Información</a>', 'https://lh3.googleusercontent.com/proxy/6E16L-9YQaHSrsRi33GsjAxCcEwMTp_ymzvq9PLXedHeTo4R9_FAcxWSU6W1c3WPH3gxV-sLZEohDHx917CoUokF6ZCL_ynVo0Js4Ro8vNnU9INC9C8NwAfty6MG2-PRo1QzcUHrE94xoLJrCxjGVfqcgEjbRqPyklMVejIqm12oTlBR6Gg');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (2, 'Facultad de CC. Económicas, Empresariales y Turismo', (ST_SetSRID(ST_MakePoint(40.479818, -3.370668), 4326)::geography), '<br>Colegio de Mínimos<br>Plaza de la Victoria, 4<br>28802 Alcalá de Henares<br>91 885 5195<br><br><a href="http://www.uah.es/economicas/index.asp" target="_blank">Ver página</a><br><br>Titulaciones en el edificio:<br><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=103&plan=G340" target="_blank">Grado en Administración y Dirección de Empresas  (Alcalá de Henares)</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=103&plan=G341" target="_blank">Grado en Contabilidad y Finanzas</a> <br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=103&plan=G360" target="_blank">Grado en Economía</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=103&plan=G361" target="_blank">Grado en Economía y Negocios Internacionales</a> <br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=103&plan=G401" target="_blank">Doble Grado en Derecho y Administración y Dirección de Empresas</a>', 'https://lh5.googleusercontent.com/proxy/CcrSBBIJhf9d5CcEFMse4Go914zy6qquE4AIaAtphIF6Gol6qI1Hfl0DUa3tnmFY1uy4Hgk8Tq5H-BvTVgpNzL9IfJeIXWxHoHpQQ2W1jyu7HYr2GAYIhdASeKPEBx5_S651Z6FArk_g80o2u59fdD71foDKfVgG8C207op_-XxT9NE1ZmJ6Qkk77QbBnTasu10q9UDFvzF6HwgW');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (3, 'Facultad de Derecho', (ST_SetSRID(ST_MakePoint(40.485166, -3.361571), 4326)::geography), '<br>Colegio Máximo De los Jesuitas<br>Calle de Libreros / Plaza de Puerta de Mártires, 28801 Alcala de Henares, España<br>91 885 4308 / 4309<br><br><a href="http://www.uah.es/derecho/index.asp" target="_blank">Ver página</a><br><br>Titulaciones en este edificio:<br><br>- <a href="http://www.uah.es/derecho/estudios/licenciaturas/titulaciones.htm#grado" target="_blank">Grado en Derecho</a><br>- <a href="http://www.uah.es/derecho/estudios/licenciaturas/titulaciones.htm#doble" target="_blank">Doble Grado en Derecho y Administración y Dirección de Empresas</a>', 'https://lh6.googleusercontent.com/proxy/r1lKkttYNSqQlDuPh1NBwLEkFHKfOkzPcJ6qTTUogc8Bem_Xrkf79HzYW8DwMi1HWK_049D_tAYJtovjfEFAKsC6sl_bvakg-V3cr_fDc5iFFTAR5euSx4UGX1I6UDpaKITVEVjwlFeBR7wgaGOqXuKjiO5f9NWzG5u6J0Cb6EtswWVGgsIXwG6QhkOYFDu70V1l9yzugh-Mp4yHxoKlLVwh-YVRwErEAb0mPekwZrW3vtWI31Tcomv8NZI');


INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (4, 'Facultad de Filosofía y Letras', (ST_SetSRID(ST_MakePoint(40.48126, -3.363725), 4326)::geography), '<br>Colegio de Malaga<br>Calle Colegios, 2<br>28801 Alcalá de Henares<br>91 885 4432<br><br><a href="http://www.uah.es/filosofiayletras/index.asp" target="_blank">Ver página</a><br><br>Titulaciones en el edificio:<br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=106&plan=G250" target="_blank">Grado en Historia</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=106&plan=G252" target="_blank">Grado en Humanidades</a>', 'https://lh6.googleusercontent.com/proxy/zmwrD8P9VNGlRqE8fVI7nK4yQw-q5xF2F3ahWKXu-U206yi0q4S9K9QKbR010GBtcdgPO0oOsIp7ojMI6gFzYEq7nXcAuBxu9_6Lvey1rm9IkSYJGHpqHLsotKwwMXNCRzWj_yJ5qJdoRNMo8scLT_C2EJEKIRNY9oZzNkVB6oTyMJrV32yC5bTvO0og3-tg8USkai1dyCod8cp4SACbwmmLqeEhTAlSipcriDydEcU5WaXZKtObp-cN_SYrmQf-NLOCFUmOae8Q');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (5, 'Facultad de Medicina y CC. de la Salud - Enfermería y Fisioterapia', (ST_SetSRID(ST_MakePoint(40.512749, -3.346445), 4326)::geography), '<br>Calle 19<br>28805 Alcalá de Henares, Madrid<br>91 885 46 69/50/10<br><br><a href="http://www.uah.es/enfermeria/" target="_blank">Ver página - Enfermería</a><br><a href="http://www.uah.es/fisioterapia/" target="_blank">Ver página - Fisioterapia</a><br><br>Titulaciones en este edificio:<br><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=205&plan=G209" target="_blank">Grado en Enfermería</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=205&plan=G249" target="_blank">Grado en Fisioterapia</a><br>Pertenecientes a la Facultad', 'https://lh5.googleusercontent.com/proxy/0uBlgkvOCXEhn3inMsLzz2J8yPiym4hMFhUex2m35tXiEFK02l8_Co-KMRmJFcBM20P34pjRcl12z6MmSB6Ptwx5yygAmw9RZl2sv3ouS2eK7TuWxPKtSpnXatXuz8-Mhs7DEHjfx9GcC2vZ5_O5vGdGK2MHhHdhoPBBHllZVbi62hB_nZ9RxZypDFHIYmd9i5d5rRN0fVYlm6AW7XEeTobM6TyYhTDY244lqITNf-l0fnNBHvqVMjK8gA');


INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (6, 'Facultad de Medicina y Ciencias de la Salud - Edificio de Medicina y CAFIDE', (ST_SetSRID(ST_MakePoint(40.511501, -3.345066), 4326)::geography), '<br>Calle 19, 3<br>28805 Alcalá de Henares, Madrid<br>91 885 4505, 91 885 4855<br><br><a href="http://www.uah.es/medicina/index.asp" target="_blank">Ver Página - Medicina </a><br><a href="http://www.uah.es/ccafyde/index.asp" target="_blank">Ver Página - CCAFYDE</a><br><br>Titulaciones en el edificio:<br><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=101&plan=G215&nombreplan=Grado%20en%20Medicina" target="_blank">Grado en Medicina</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=101&plan=G770&nombreplan=Grado%20en%20Ciencias%20de%20la%20Actividad%20F%C3%ADsica%20y%20del%20Deporte" target="_blank">Grado en Ciencias de la Actividad Física y del Deporte</a>', 'https://lh5.googleusercontent.com/proxy/fZ0UkJOh5ZZK8N7EMyYN1zX3fQNbS_w-NLMokjcPW0owJRM6iMedWyX9dezsTG5eeiVnqCueMiThSl_RPS8LDdNO4rQZ5blK9j8mLegzng542ts1m6sBvCrCxfKe44UvXv0g_HYepPZqgGl321bYWa9aGFdAHvW0agQHnE4f941QQmTBVZckXJKm');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (7, 'Facultad de Biología, Ciencias Ambientales y Química. Edificio de Ambientales', (ST_SetSRID(ST_MakePoint(40.510035, -3.345184), 4326)::geography), '<br>Calle 19<br>28805 Alcalá de Henares, Madrid<br>91 885 5113<br><br><a href="http://www.uah.es/ambientales/index.asp" target="_blank">Ver Página - Ambientales</a><br><br>Titulaciones en el edificio:<br><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=107&plan=G670" target="_blank">Grado en Ciencias Ambientales. Plan G670</a>', 'https://lh4.googleusercontent.com/proxy/XlDR0MRU23DHzmT34-dM400fK7a9vu15hVD_Exe3saUrZFlgEWeQpQ8TUZkcl2jQ45yGWc5aW5bpN5xZt-RRUf2V0cbbELgmTI1s5-HI6qogwQJ7n6AGKDcmKLKkA9uKjPHAAfx1BjBA2fluEmkWE6p7ZOuGQ_RAR7WaLjI31W-ZUd1RmeYB86BQ9Bg8HA');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (8, 'Facultad de Farmacia', (ST_SetSRID(ST_MakePoint(40.509558, -3.342075), 4326)::geography), '<br>Calle 20 <br>28805 Alcalá de Henares, Madrid<br>91 885 4680<br><br><a href="http://www.uah.es/farmacia/" target="_blank">Ver Página - Farmacia</a><br><br>Titulaciones en el edificio:<br><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=104&plan=G57" target="_blank">Grado en Farmacia</a>', 'https://lh5.googleusercontent.com/proxy/3_1RoDjFqp5MsqjL3nauhuX7KzQ2f5n8YrgVyLljhK4o_t81dwtnKVfph7vaa8orQb-nntOXykVjBpVZ3akt513rKC7hrUyRS9OyEZV4yrh4GyYyQ7oAYhokXeh2F21NihTjho7XtxsUlyGbKXTzQaBh0hPSj8YQS6xeBucMjLcdYmxJ5MSzPe2hdw');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (9, 'Facultad de Biología, Ciencias Ambientales y Química - Edificio de Biología', (ST_SetSRID(ST_MakePoint(40.505471, -3.336936), 4326)::geography), '<br>Edificio de Ciencias<br>Calle 24<br>28805 Alcalá de Henares, Madrid<br>91 885 4916 <br><br><a href="http://www.uah.es/biologia/index.asp" target="_blank">Ver Página</a><br><br>Titulaciones en este edificio:<br><br><a href="http://www.uah.es/estudios/grados/planes.asp?cd=102&plan=G650" target="_blank">Grado en Biología</a><br><a href="http://www.uah.es/estudios/grados/planes.asp?cd=102&plan=G651" target="_blank">Grado en Biología Sanitaria</a>', 'http://gerencia.uah.es/imagenes/facultades/ciencias.jpg' );


INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (10, 'Facultad de Educación', (ST_SetSRID(ST_MakePoint(40.63765, -3.169749), 4326)::geography), '<br><br>Titulaciones en el edificio:<br> <br><a href="http://www.uah.es/facultad-educacion/" target="_blank">Estudios pertenecientes a la Facultad de Educación</a>:<br><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=202&plan=G420&nombreplan=Grado%20en%20Magisterio%20de%20Educaci%F3n%20Infantil" target="_blank">Grado en Magisterio de Educación Infantil.</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=202&plan=G430&nombreplan=Grado%20en%20Magisterio%20de%20Educaci%F3n%20Primaria" target="_blank">Grado en Magisterio de Educación Primaria</a> (posibilidad de cursar el grado bilingüe)<br><a href="http://www.uah.es/estudios/grados/planes.asp?cd=109&plan=G641" target="_blank">Estudios pertenecientes a la Facultad Filosofía y Letras</a>:<br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=109&plan=G641" target="_blank">Grado en Comunicación Audiovisual</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=106&plan=G440&origen=estudios&T=ARTES_Y_HUMANIDADES" target="_blank">Grado en Lenguas Modernas y Traducción.</a>', 'https://lh6.googleusercontent.com/proxy/6Cu-Gnk9U-omlxIZ6ci874Ork8FXWzVUZ1gq_uwRIPg_tNklmBVAalRKRjlRd61cPNRvNqyL0ZjnR3sJaoCfws7eGg8FumPVPJvOGNPoy-GypfZ8PgFz_5qyWn8gZKYqDCOWiLlY0B2qYFYtqzBV43x6REABsg2gF2jkAsf-DhQGmDnWhiQyM1Zjyck');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (11, 'Escuela de Arquitectura', (ST_SetSRID(ST_MakePoint(40.481164, -3.365293), 4326)::geography), '<br>Convento del Carmen Calzado<br>Santa Úrsula, 8<br>28801 Alcalá de Henares, Madrid<br>91 883 92 56<br> <br><a href="http://www.uah.es/escuela-arquitectura/" target="_blank">Ver Página</a><br><br>Titulaciones en el edificio:<br><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=209&plan=G256&origen=estudios&T=INGENIERIA_Y_ARQUITECTURA" target="_blank">Grado en Fundamentos de Arquitectura y Urbanismo + Máster en Arquitectura</a><br>- <a href="http://www2.uah.es/geodesia_cartografia/Inicio/Titulaciondocente.html" target="_blank">Ingeniería superior en Geodesia y Cartografía</a>', 'https://lh4.googleusercontent.com/proxy/1FvKsHGvpbvdXgNEPeAK-kXOFzJ5dNngsONGblR8OOtwAnsGKwpTDVqt5bNHjmfgxUCBdy_mT3Gw2wm4aCwFgO_tKyqbBuYPhChMe06j7QBDJDQ4L2d8WJcbMuN7VXL4sO6_GUDmnjRIWhrEifGTpkLy4CMqpE_EuULZtn9hIGFwTDlOK0lK90uTzoJW8efqylj0kM7WlMX6ifaQDPR41rbNAfc');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (12, 'Facultad de Filosofía y letras', (ST_SetSRID(ST_MakePoint(40.479459, -3.360647), 4326)::geography), '<br>Aulario María de Guzmán <br>C/ San Cirilo, s/n. <br>28801 Alcalá de Henares, Madrid <br>91 885 50 00<br><br><a href="http://www.uah.es/documentacion/index.asp" target="_blank">Ver Página</a>', 'https://lh6.googleusercontent.com/proxy/s6nC4u6LHXiqgJ7WTuwsOMgQFzjTqkjGIOZFOes5Wuhm9yJ4tIgjQnqyR8CYoiRmFSnuU4bNY9aiRK_RIFBB69QZbG0zG_q4ZpuOMneU6cOPWIax6fqs0E3NwXbK8r3lDhtBxKAFR1op6eqrtORGY8ufMRdipY5dfNZQ5N2AOHGZcYBW-3DSC5r2s0QguPp4VsKwkQLRXqWfWjUzQsr_uh-aGvFM3YE_fm8VZy9BItmTlpeeLMDY0loSi9sZDOd6h9wfswaJs_yQZUmSlR2W1RwxeSXhjuWt8zU');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (13, 'Facultad de Biología, Ciencias Ambientales y Química de la Universidad de Alcalá', (ST_SetSRID(ST_MakePoint(40.5107, -3.341705), 4326)::geography), '<br>Edificio Polivalente, Campus Científico-Tecnológico  <br>Ctra. Madrid-Barcelona Km 33,600. E-28871 Alcalá de Henares (Madrid) <br>Teléfono:+34 918854905| Fax: +34 918854936 <br>', 'https://lh6.googleusercontent.com/proxy/tnlnvlWN9UCPBWCRzYsaO-DDEpTTchftiVE_8x7_IOyIDofBr5J1hK6clr41vsBzA_gPptv1hBRM4sSffe0Dc1utGGV4KQJ3wO19FpayWFMM0Q');

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (14, 'Facultad de Filosofía y Letras - Colegio Caracciolos', (ST_SetSRID(ST_MakePoint(40.48021, -3.365169), 4326)::geography), '<br>Calle de la Trinidad 3-5<br>28801 Alcalá de Henares<br>Madrid<br><br><br>Titulaciones que se imparten:<br><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=106&plan=G440&origen=estudios&T=ARTES_Y_HUMANIDADES" target="_blank">Grado en Lenguas Modernas y Traducción</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=106&plan=G790&origen=estudios&T=ARTES_Y_HUMANIDADES" target="_blank">Grado en Estudios Hispánicos</a><br>- <a href="http://www.uah.es/estudios/grados/planes.asp?cd=106&plan=G251&origen=estudios&T=ARTES_Y_HUMANIDADES" target="_blank">Grado en Estudios Ingleses</a>', 'https://lh5.googleusercontent.com/proxy/2nbb60lwcXqidtY9RfSyLMxrsBc9KEe5AQyrHpglh0f9KgWyyvF-pcqIOTg9n7ewfcJu_1tzKnPzgeDyy5PEnmBbTPqMV13dgbjnG3Jp-1W2UrOQMYqX9v5jtZZve6q5ZqQtU-9L7o5SFirv5g' );

INSERT INTO facultades (id, nombre, ubicacion, descripcion, imagen) VALUES (15, 'Facultad de Filosofía y Letras - Colegio de los Trinitarios', (ST_SetSRID(ST_MakePoint(40.480675, -3.363919), 4326)::geography), '<br>Calle Trinidad 1-3<br>28801 Alcalá de Henares<br>Madrid', 'https://lh5.googleusercontent.com/proxy/oZbsAaGlkQjgYK-uCU6KzpIp7-Y3XCoT4cW2zHxyYguJJUts9gCxo5r_99Lny9dQPAA9QZRq5fal40ZhSEp6eoIUBEfWOz7VcSc');
